#!/usr/bin/env bash

CACHE=~/docker-cache

mkdir -p $CACHE

images=(codeclimate duplication csslint eslint fixme nodesecurity markdownlint shellcheck editorconfig)


save () {
  local image=${1}

  if [ $image = "codeclimate" ]; then
    source=ahmadnassri/codeclimate:fail-on-exit
  else
    source=codeclimate/codeclimate-$image
  fi

  docker pull $source

  echo "saving $image"
  docker save -o $CACHE/$image.tar $source

  load $image
}

load () {
  echo "loading $1"
  docker load -i $CACHE/$1.tar &>/dev/null
}

for image in "${images[@]}"
do
test -f $CACHE/$image.tar && load $image || save $image
done
